name: spec_app
description: "SpecDoor app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0-85.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  get: ^4.6.6
  auto_route: ^9.2.2
  get_it: ^8.0.2
  injectable: ^2.5.0
  go_router: ^14.4.1
  freezed_annotation: ^2.4.4
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.6
  csv: ^6.0.0
  file_saver: ^0.2.14
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0
  injectable_generator: ^2.6.2
  freezed: ^2.5.7
  json_serializable: ^6.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
    - assets/logos/