// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUhQjWv1Ejp3JHv48SkZOhgldraOIuzlk',
    appId: '1:873908260201:web:a81c40f44a581fe7a381f8',
    messagingSenderId: '873908260201',
    projectId: 'specapp-4d24b',
    authDomain: 'specapp-4d24b.firebaseapp.com',
    storageBucket: 'specapp-4d24b.firebasestorage.app',
    measurementId: 'G-GER2BJ9YDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATkVdgRP6NLfnTg5W7yl-E69PE9k5Y2Bk',
    appId: '1:873908260201:android:9e0a8b4a98b4efeaa381f8',
    messagingSenderId: '873908260201',
    projectId: 'specapp-4d24b',
    storageBucket: 'specapp-4d24b.firebasestorage.app',
  );

}